version: '3.8'
services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "8080:5173"
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
